### ISSUE TITLE
Invalid `Podfile` file: undefined class/module Digest.

### ISSUE THREAD

**Issue by cyrilkyburz** [faberNovel/ad_licenselint#14]
Hi, first thank you for your library. 

We encountered an issue when using your library in a react native project. We are using ruby 2.7.3 with cocoapods 1.10.1.

```sh
bundle exec ad_licenselint -p './ios'
bundler: failed to load command: ad_licenselint (/Users/cyril/.rbenv/versions/2.7.3/bin/ad_licenselint)
Pod::DSLError:
[!] Invalid `Podfile` file: undefined class/module Digest.
```

But when we change the dependecy in the [ad_licenselint.rb](https://github.com/faberNovel/ad_licenselint/blob/master/lib/ad_licenselint.rb) file from 

```ruby
require 'cocoapods-core'
```

to

```ruby
require 'cocoapods'
```

it works.

Is it an option if we change the dependency from cocoapods-core to cocoapods? Would you welcome a PR?

**Comment by felginep** [comment]
Hi, thanks for the issue.

Can you try to run the following commands, instead of using the `-p` argument and give me the results ?

```
cd ios
bundle exec ad_licenselint
```

I see a different behavior between the two on a react native project on my side.

**Comment by felginep** [comment]
But you are right, requiring `cocoapods` instead of `cocoapods-core` seems to fix the issue. I'm not sure why the Podfile is not correctly evaluted with `cocoapods-core` only though.
I'll push a PR soon to fix this.

**Comment by felginep** [comment]
Should be good on [v1.3.0](https://github.com/faberNovel/ad_licenselint/releases/tag/v1.3.0)
